services:

  mariadb:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE:      "${MYSQL_DATABASE}"
      MYSQL_USER:          "${MYSQL_USER}"
      MYSQL_PASSWORD:      "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "sh", "-c", "mariadb --host=127.0.0.1 --user=root --password=\"$MYSQL_ROOT_PASSWORD\" --execute=\"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
       context: .
       dockerfile: ./API/Dockerfile

    env_file:
      - .env.local
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_URLS:        "http://+:80"
      ASPNETCORE_ENVIRONMENT: "Development"
      MYSQL_HOST:             "mariadb"
      MYSQL_DATABASE:         "${MYSQL_DATABASE}"
      MYSQL_USER:             "${MYSQL_USER}"
      MYSQL_PASSWORD:         "${MYSQL_PASSWORD}"
      SEQ_URL:                "${SEQ_URL}"  
      FEATUREHUB_URL:         "${FEATUREHUB_URL}"
      FEATUREHUB_API_KEY:     "${FEATUREHUB_API_KEY}"
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    restart: on-failure

  flyway:
    image: flyway/flyway:latest
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./db/migration:/flyway/sql
    command: migrate
    environment:
      FLYWAY_URL:      jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}
      FLYWAY_USER:     ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    env_file:
      - ./Frontend/.env.local
    ports:
      - "3000:8080"
    depends_on:
      backend:
        condition: service_started

volumes:
  mariadb_data:
