name: Hello-World Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build & push Docker image
        run: docker build -t hello-frontend ./frontend

      - name: Copy compose & frontend to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: |
            docker-compose.yml
            frontend/**
          target:   "~/todo-bare"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd ~/todo-bare
            docker compose up -d --build

