name: E2E-Tests

on:
  workflow_run:
    workflows: ["Build and Deploy to Staging"]
    types:
      - completed

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 20

      - name: Install Chromium & dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libnss3 libxss1 fonts-liberation

      - name: Install TestCafe
        run: npm install -g testcafe

      - name: Run TestCafe E2E tests
        env:
          STAGING_REACT_URL: "http://141.147.1.249:3000"
        run: |
          testcafe 'chromium:headless' E2E/e2eTest.js --reporter spec --json-report testcafe-result.json

      - name: Upload TestCafe report
        uses: actions/upload-artifact@v4
        with:
          name: TestCafeReport
          path: testcafe-result.json
